--- #YAML:1.0
name: Math-Fractal-Mandelbrot
version: 0.03
version_from: lib/Math/Fractal/Mandelbrot.pm
license: perl
distribution_type: module
generated_by: Math-Fractal-Mandelbrot version 0.03
installdirs: perl
requires: {}
